name: afkar
description: A new Flutter project.

version: 4.0.0+4

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  custom_radio_grouped_button: ^1.0.0
  webview_flutter: ^0.3.22+1
  cached_network_image: ^2.2.0+1
  firebase_messaging: ^7.0.0
  dio: ^3.0.9
  mime: ^0.9.6+3
  provider: ^4.0.4
  image_picker: ^0.6.5+3
  http: ^0.12.1
  shared_preferences: ^0.5.7
  country_code_picker: ^1.3.12+1
  grouped_buttons: ^1.0.4
  material_dropdown_formfield: ^0.1.4
  fluttertoast: ^4.0.1
  intl: ^0.16.1
  flutter_local_notifications: ^1.4.4+4
  rxdart: ^0.24.1
  permission_handler: ^5.0.1+1
  file_picker: ^1.13.3
  path_provider: ^1.6.11
  pdf_flutter: ^1.1.3
  flutter_downloader: ^1.5.0
  pdf: ^1.8.1
  printing: ^3.5.0

  #dropdownfield: ^1.0.3
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - images/
   - fonts/


  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf
        - asset: fonts/Hacen-Egypt.ttf
        - asset: fonts/Tajawal-Medium.ttf